[package]
name = "yukino"
version = "0.1.0"
authors = ["dark-flames <dark_flames@outlook.com>"]
edition = "2018"

[dependencies]
model = { package = "yukino-model", path = "model", version = "0.1.0" }

[dev-dependencies]
rusty-hook = "^0.11.2"

[lib]

[workspace]
members = [
    "model"
]
